zx-v0.50

diff --git a/.github/workflows/web-backend-cicd.yml b/.github/workflows/web-backend-cicd.yml
--- a/.github/workflows/web-backend-cicd.yml
+++ b/.github/workflows/web-backend-cicd.yml
@@ -8,7 +8,6 @@ on:
     branches:
       - main
 
-
 jobs:
   build:
     runs-on: ubuntu-latest
@@ -45,36 +44,34 @@ jobs:
             exit 1
           fi
 
-##             **缓存 NVD 数据库**
-#      - name: Cache OWASP Dependency-Check Data
-#        uses: actions/cache@v3
-#        with:
-#          path: ~/.dependency-check
-#          key: dependency-check-${{ runner.os }}-${{ hashFiles('**/dependency-check.properties') }}
-#          restore-keys: |
-#            dependency-check-${{ runner.os }}-
-#
-#          # **SAST配置：依赖检查**
-#      - name: Run Dependency Check
-#        run: |
-#          mkdir -p reports
-#          mvn org.owasp:dependency-check-maven:check -Dformat=ALL -Dout=reports/
-#
-#      - name: Upload Dependency Check Report
-#        if: always()
-#        uses: actions/upload-artifact@v4
-#        with:
-#          name: dependency-check-report
-#          path: reports/dependency-check-report.xml
-#
-#      - name: Fail on High Vulnerabilities
-#        run: |
-#          if grep -q '<severity>Critical</severity>\|<severity>High</severity>' reports/dependency-check-report.xml; then
-#            echo "High or Critical vulnerabilities found!"
-#            exit 1
-#          fi
+      # 缓存 NVD 数据库
+      # - name: Cache OWASP Dependency-Check Data
+      #   uses: actions/cache@v3
+      #   with:
+      #     path: ~/.dependency-check
+      #     key: dependency-check-${{ runner.os }}-${{ hashFiles('**/dependency-check.properties') }}
+      #     restore-keys: |
+      #       dependency-check-${{ runner.os }}-
 
-    
+      # SAST配置：依赖检查
+      # - name: Run Dependency Check
+      #   run: |
+      #     mkdir -p reports
+      #     mvn org.owasp:dependency-check-maven:check -Dformat=ALL -Dout=reports/
+
+      # - name: Upload Dependency Check Report
+      #   if: always()
+      #   uses: actions/upload-artifact@v4
+      #   with:
+      #     name: dependency-check-report
+      #     path: reports/dependency-check-report.xml
+
+      # - name: Fail on High Vulnerabilities
+      #   run: |
+      #     if grep -q '<severity>Critical</severity>\|<severity>High</severity>' reports/dependency-check-report.xml; then
+      #       echo "High or Critical vulnerabilities found!"
+      #       exit 1
+      #     fi
 
       # 登录 Docker 并推送镜像
       - name: Log in to Docker Hub
@@ -86,12 +83,11 @@ jobs:
 
       - name: Push Docker Image
         run: docker push ${{ secrets.DOCKER_USERNAME }}/web-backend:latest
-#        2
 
   deploy:
     needs: build
     runs-on: ubuntu-latest
-#3
+
     steps:
       - name: Deploy to EC2
         uses: appleboy/ssh-action@master
@@ -103,8 +99,7 @@ jobs:
             docker stop web-backend || true
             docker rm web-backend || true
             docker rmi -f ${{ secrets.DOCKER_USERNAME }}/web-backend || true
-#            sleep 10
             docker pull web-backend:latest
             docker run -d --name web-backend -p 5000:5000 web-backend:latest
-#            docker run -d --name web-backend -p 5000:5000 --restart always web-backend:latest
-#            docker start web-backend:latest
+            # docker run -d --name web-backend -p 5000:5000 --restart always web-backend:latest
+            # docker start web-backend:latest
